// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandPitchAngle.proto

#ifndef PROTOBUF_INCLUDED_CommandPitchAngle_2eproto
#define PROTOBUF_INCLUDED_CommandPitchAngle_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_CommandPitchAngle_2eproto 

namespace protobuf_CommandPitchAngle_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_CommandPitchAngle_2eproto
namespace mav_msgs {
namespace msgs {
class CommandPitchAngle;
class CommandPitchAngleDefaultTypeInternal;
extern CommandPitchAngleDefaultTypeInternal _CommandPitchAngle_default_instance_;
}  // namespace msgs
}  // namespace mav_msgs
namespace google {
namespace protobuf {
template<> ::mav_msgs::msgs::CommandPitchAngle* Arena::CreateMaybeMessage<::mav_msgs::msgs::CommandPitchAngle>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mav_msgs {
namespace msgs {

// ===================================================================

class CommandPitchAngle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mav_msgs.msgs.CommandPitchAngle) */ {
 public:
  CommandPitchAngle();
  virtual ~CommandPitchAngle();

  CommandPitchAngle(const CommandPitchAngle& from);

  inline CommandPitchAngle& operator=(const CommandPitchAngle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CommandPitchAngle(CommandPitchAngle&& from) noexcept
    : CommandPitchAngle() {
    *this = ::std::move(from);
  }

  inline CommandPitchAngle& operator=(CommandPitchAngle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommandPitchAngle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CommandPitchAngle* internal_default_instance() {
    return reinterpret_cast<const CommandPitchAngle*>(
               &_CommandPitchAngle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CommandPitchAngle* other);
  friend void swap(CommandPitchAngle& a, CommandPitchAngle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CommandPitchAngle* New() const final {
    return CreateMaybeMessage<CommandPitchAngle>(NULL);
  }

  CommandPitchAngle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CommandPitchAngle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CommandPitchAngle& from);
  void MergeFrom(const CommandPitchAngle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommandPitchAngle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float pitch_angle = 1 [packed = true];
  int pitch_angle_size() const;
  void clear_pitch_angle();
  static const int kPitchAngleFieldNumber = 1;
  float pitch_angle(int index) const;
  void set_pitch_angle(int index, float value);
  void add_pitch_angle(float value);
  const ::google::protobuf::RepeatedField< float >&
      pitch_angle() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_pitch_angle();

  // @@protoc_insertion_point(class_scope:mav_msgs.msgs.CommandPitchAngle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > pitch_angle_;
  mutable int _pitch_angle_cached_byte_size_;
  friend struct ::protobuf_CommandPitchAngle_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CommandPitchAngle

// repeated float pitch_angle = 1 [packed = true];
inline int CommandPitchAngle::pitch_angle_size() const {
  return pitch_angle_.size();
}
inline void CommandPitchAngle::clear_pitch_angle() {
  pitch_angle_.Clear();
}
inline float CommandPitchAngle::pitch_angle(int index) const {
  // @@protoc_insertion_point(field_get:mav_msgs.msgs.CommandPitchAngle.pitch_angle)
  return pitch_angle_.Get(index);
}
inline void CommandPitchAngle::set_pitch_angle(int index, float value) {
  pitch_angle_.Set(index, value);
  // @@protoc_insertion_point(field_set:mav_msgs.msgs.CommandPitchAngle.pitch_angle)
}
inline void CommandPitchAngle::add_pitch_angle(float value) {
  pitch_angle_.Add(value);
  // @@protoc_insertion_point(field_add:mav_msgs.msgs.CommandPitchAngle.pitch_angle)
}
inline const ::google::protobuf::RepeatedField< float >&
CommandPitchAngle::pitch_angle() const {
  // @@protoc_insertion_point(field_list:mav_msgs.msgs.CommandPitchAngle.pitch_angle)
  return pitch_angle_;
}
inline ::google::protobuf::RepeatedField< float >*
CommandPitchAngle::mutable_pitch_angle() {
  // @@protoc_insertion_point(field_mutable_list:mav_msgs.msgs.CommandPitchAngle.pitch_angle)
  return &pitch_angle_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace mav_msgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_CommandPitchAngle_2eproto
